### PR TITLE
Bulk perform tracking machty

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
rebased bulk-perform-3-6 on matchy/1.2.1

the inverse PR: https://github.com/machty/ember-concurrency/compare/master...CrowdStrike:bulk-perform-3-6?expand=1

### CODE REVIEW

**Comment by kellyselden** [comment]
I'd prefer to track latest released rather than latest master.

**Comment by NullVoxPopuli** [comment]
done

**Comment by kellyselden** [comment]
I made a new branch for you to target `bulk-perform-3-12` (based on ember 3.12 being in the package.json of your PR).

**Comment by NullVoxPopuli** [comment]
Why 3.12? The ember version has nothing to do with the concurrency version. Specifically, there are fixes we need that resolve cycles in Autotracking -- while still being back compat

**Comment by NullVoxPopuli** [comment]
Updated target

**Comment by kellyselden** [comment]
I was just using the existing naming convention. Something that can also be incremented for any new work or rebase. Do you have a different branch name in mind?

**Comment by NullVoxPopuli** [comment]
ultimately, I want to get off the use of a fork anyway -- based on a conversation with the ember-concurrency folks, it's gonna be a while before they'd be willing to accept any new features -- _and_ since we use our custom code in one place, I think it'd just be easier for everyone to to move into our user-space, rather than pushing responsibility of maintenance upstream.

**Pull request merged**
